#!/bin/bash
#---
## by Bor Kraljič <pyrobor[at]ver[dot]si>
## Licence is GPL v2 or higher
##
## bash_completion for my short commands and some guru tools
##
#---
[ -f /etc/bash_completion.d/smgl_completion ] &&
eval `. /etc/bash_completion.d/smgl_completion`

_installed_spells()
{
    local cur prev
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
	_add_installed_spell_list
    return 0

}

_all_spells()
{
    local cur prev
    COMPREPLY=()
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
	_spell_list
    return 0
}

#----------------------------------------------------------
## alias section
##
#----------------------------------------------------------
have gt && complete -F _installed_spells -o default gt
have gw && complete -F _all_spells -o default gw
have gv && complete -F _all_spells -o default gv
have gu && complete -F _all_spells -o default gu
have gl &&  complete -F _all_spells -o default gl
have gvs && complete -F _all_spells -o default gvs
have gh && complete -F _all_spells -o default gh
have gil && complete -F _installed_spells -o default gil
have gcl && complete -F _installed_spells -o default gcl



#----------------------------------------------------------
## SCRIPTS section
##
#----------------------------------------------------------
have resignsources.sh && complete -F _all_spells -o default resignsources.sh
have copy_spells_git2grim.sh && complete -F _all_spells -o default copy_spells_git2grim.sh
have spells_massinfo.sh && complete -F _all_spells -o default spells_massinfo.sh
#have git spelllog && complete -F _all_spells -o default git spelllog


# for script find_nonexisting_dependencies
have find_nonexisting_dependencies &&
_find_nonexisting_dependencies() {
    COMPREPLY=()
    local cur prev
    _get_comp_words_by_ref cur prev

    if [[ "$cur" == -* ]] ; then
        COMPREPLY=( $( compgen -W "$( _parse_help "$1" )" -- "$cur" ) )
    else
        _filedir
    fi
} &&
complete -F _find_nonexisting_dependencies find_nonexisting_dependencies

#---
## fastcommit.sh
## simple completion from help msg
#---
have fastcommit.sh &&
_fastcommit() {
    COMPREPLY=()
    local cur prev
    _get_comp_words_by_ref cur prev

    if [[ "$cur" == -* ]] ; then
        COMPREPLY=( $( compgen -W "$( _parse_help "$1" )" -- "$cur" ) )
    fi
} &&
complete -F _fastcommit fastcommit.sh



#---
## gpg_edit_keyring
## complete with gpg keyrings
#---
have gpg_edit_keyring &&
_gpg_edit_keyring() {
  COMPREPLY=()
  local cur prev
  _get_comp_words_by_ref cur prev

  if [[ "$cur" == -* ]] ; then
    COMPREPLY=( $( compgen -W "$( _parse_help "$1" )" -- "$cur" ) )
  fi

  case $prev in
    -k|-m|--keyring|--minimize)
      _filedir gpg
      ;;
    -h|--help)
      return 0
      ;;
  esac

} &&
complete -F _gpg_edit_keyring gpg_edit_keyring


#---
## renameFiles.sh
## simple completion from help msg
#---
have renameFiles.sh &&
_renamefiles_sh() {
    COMPREPLY=()
    local cur prev
    _get_comp_words_by_ref cur prev

    if [[ "$cur" == -* ]] ; then
        COMPREPLY=( $( compgen -W "$( _parse_help "$1" )" -- "$cur" ) )
    fi
} &&
complete -F _renamefiles_sh renameFiles.sh

#----------------------------------------------------------
## GURU-TOOLS SECTION
##
#----------------------------------------------------------


#---
## checkGrimoire.sh
## simple completion from help msg
#---
have checkGrimoire.sh &&
_checkgrimoire() {
    COMPREPLY=()
    local cur prev
    _get_comp_words_by_ref cur prev

    if [[ "$cur" == -* ]] ; then
        COMPREPLY=( $( compgen -W "$( _parse_help "$1" )" -- "$cur" ) )
    fi
} &&
complete -F _checkgrimoire checkGrimoire.sh

#---
## hashcheck.sh
## simple completion from help  msg and spellname after that
#---
have hashcheck.sh &&
_hashcheck() {
  COMPREPLY=()
  local cur prev
  _get_comp_words_by_ref cur prev

    if [[ "$cur" == -* ]] ; then
        COMPREPLY=( $( compgen -W "$( _parse_help "$1" )" -- "$cur" ) )
    else
      _all_spells
    fi
} &&
complete -F _hashcheck hashcheck.sh

#---
## smgl-keyring-diff
## complete with gpg keyrings
#---
have smgl-keyring-diff &&
_smgl-keyring-diff() {
  COMPREPLY=()
  local cur prev
  _get_comp_words_by_ref cur prev

  _filedir gpg
} &&
complete -F _smgl-keyring-diff smgl-keyring-diff

#---
## findSharedFiles
## simple completion from help msg
#---
have findSharedFiles &&
_findSharedFiles() {
    COMPREPLY=()
    local cur prev
    _get_comp_words_by_ref cur prev

    if [[ "$cur" == -* ]] ; then
        COMPREPLY=( $( compgen -W "$( _parse_help "$1" )" -- "$cur" ) )
    fi
} &&
complete -F _findSharedFiles findSharedFiles

